apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: redis-pod-delete
  namespace: sample-app
spec:
  appinfo:
    appns: 'sample-app'
    applabel: 'app=redis'
    appkind: 'deployment'
  # It can be active/stop
  engineState: 'active'
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '30'
            # set chaos interval (in sec) as desired
            - name: CHAOS_INTERVAL
              value: '10'
            # pod failures without stopping pod/container lifecycle
            - name: FORCE
              value: 'false'
